version: '3.3'
services:
  apache:
    build:
      context: .     
      dockerfile: ./Dockerfile
    container_name: app
    environment:
      - "APACHE_ROOT=${APACHE_ROOT_PATH}"
      - "DOMAIN=${DOMAIN_NAME}"
    volumes:
      - ./apache/php.ini:/usr/local/etc/php/php.ini
      - ./apache/policy.xml:/etc/ImageMagick-6/policy.xml
      - ~/.ssh:/home  # path to local ssh key location /home/
      - ./src:/var/www/html
      - ~/.composer/cache:/var/www/.composer/cache
      - ~/.npm:/var/www/.npm
      - ./apache/default.conf:/etc/apache2/sites-available/cashback.conf
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.apache.entrypoints=websecure
      - traefik.http.routers.apache.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.routers.apache.tls.options=default
      - traefik.http.services.apache.loadbalancer.server.port=80
    networks:
      web:
        ipv4_address: 172.20.0.11
    user: www-data:www-data

networks:
  web:
    external: true
  internal:
    external: false
